### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by mschinca** [crystalct/Ps3_Sqlite#1]
Hi @crystalct,
my build fails with output below, what am I missing?
My goal would be to setup a Ubuntu VM to be able to build [FBNeoRLPlus](https://github.com/crystalct/FBNeoRLPlus) and make some modifications. I'm using Ubuntu 16.04 and installed PSL1GHT from [binaries](https://github.com/bucanero/ps3toolchain/releases/download/ubuntu-latest-fad3b5fb/ps3dev-ubuntu-latest-2020-08-31.tar.gz).

Any help?
```
me@me-VirtualBox:~/src/Ps3_Sqlite$ make
[ -d build ] || mkdir -p build
make -C build -f /home/me/src/Ps3_Sqlite/Makefile
make[1]: Entering directory '/home/me/src/Ps3_Sqlite/build'
main.c
font_b.c
linking ... Ps3_Sqlite.elf
/opt/ps3dev/ppu/bin/../lib/gcc/powerpc64-ps3-elf/7.2.0/../../../../powerpc64-ps3-elf/bin/ld: cannot find -lps3sqlite
collect2: error: ld returned 1 exit status
/opt/ps3dev/base_rules:58: recipe for target '/home/me/src/Ps3_Sqlite/Ps3_Sqlite.elf' failed
make[1]: *** [/home/me/src/Ps3_Sqlite/Ps3_Sqlite.elf] Error 1
rm font_b.o
make[1]: Leaving directory '/home/me/src/Ps3_Sqlite/build'
Makefile:138: recipe for target 'build' failed
make: *** [build] Error 2
me@me-VirtualBox:~/src/Ps3_Sqlite$ ls build
font_b.d  main.d  main.o  Ps3_Sqlite.elf.map
```

**Comment by crystalct** [comment]
Ciao Marco, 
devi prima compilare la libreria (`make lib`)
e poi installarla in $PORTLIBS (`make install`).
A quel punto puoi compilare l'esempio (`make`).

**Comment by mschinca** [comment]
Grazie mille!
I managed to build and install the library.
On a second note, while building the example, the linking step fails with the error below.
Am I missing a dependency?

I also managed to build and run FBNeoRLPlus and run in on my PS3 via ps3load.
I have a few question, but I will ask them on the other repo.

Questo mondo è abbastanza nuovo per me, scusa se chiedo cose scontate :)
Grazie ancora!

```
me@me-VirtualBox:~/Ps3_Sqlite$ make 
[ -d build ] || mkdir -p build
make -C build -f /home/me/Ps3_Sqlite/Makefile
make[1]: Entering directory '/home/me/Ps3_Sqlite/build'
main.c
font_b.c
linking ... Ps3_Sqlite.elf
main.o:(.text.drawScene+0x3c): undefined reference to `SetFontSize'
main.o:(.text.drawScene+0x48): undefined reference to `SetCurrentFont'
main.o:(.text.drawScene+0x5c): undefined reference to `SetFontColor'
main.o:(.text.drawScene+0x74): undefined reference to `DrawString'
main.o:(.text.drawScene+0x8c): undefined reference to `SetFontColor'
main.o:(.text.drawScene+0x98): undefined reference to `SetCurrentFont'
main.o:(.text.drawScene+0xac): undefined reference to `DrawString'
main.o:(.text.drawScene+0xbc): undefined reference to `SetCurrentFont'
main.o:(.text.drawScene+0xd0): undefined reference to `SetFontColor'
main.o:(.text.drawScene+0xe4): undefined reference to `DrawString'
main.o:(.text.drawScene+0xf8): undefined reference to `DrawString'
main.o:(.text.drawScene+0x144): undefined reference to `DrawString'
main.o:(.text.LoadTexture+0x30): undefined reference to `ResetFont'
main.o:(.text.LoadTexture+0x58): undefined reference to `AddFontFromBitmapArray'
collect2: error: ld returned 1 exit status
make[1]: *** [/home/me/ps3dev/base_rules:59: /home/me/Ps3_Sqlite/Ps3_Sqlite.elf] Error 1
rm font_b.o
make[1]: Leaving directory '/home/me/Ps3_Sqlite/build'
make: *** [Makefile:139: build] Error 2
```

**Comment by crystalct** [comment]
You missed tiny3d library.
Hai dimenticato di installare la libreria tiny3d
https://github.com/wargio/tiny3D

**Comment by mschinca** [comment]
@crystalct scusa se scrivo qui ma non trovavo altro modo, volevo farti una domanda riguardo a https://github.com/crystalct/FBNeoRLPlus
Come fai a generare gli expansion packs, ad esempio [FBNeoRLPlus.New_snes9x_upgrade_v2.30_2021-04-27.pkg](https://github.com/crystalct/FBNeoRLPlus/releases/download/v2.30/FBNeoRLPlus.New_snes9x_upgrade_v2.30_2021-04-27.pkg) ?
Immagino che si debba scaricare il codice sorgente di RetroArch da qualche parte, applicare le patch e compilarlo, giusto?
Serve il Sony SDK o basta PSL1GHT?
Mi piacerebbe provare ad aggiungere un core per NES.

**Comment by crystalct** [comment]
I core Retroarch per PS3 funzionano bene solo compilandoli con la libreria PSQL e quindi col vecchio SDK (forse in futuro avremo la piena compatibilità di retroarch col PSL1GHT). Quindi si devono essere patchati e compilati con quell'SDK. Una volta che sono i versione SELF possono essere sfruttati dal frontend FBNEo RL Plus che è compilato con PSL1GHT (ultima versione col GCC 7.x).
Ha un bel pezzo che non ho il tempo di fare alcuni aggiornamenti, ma in futuro aggiorno un po' di cose ed era mia intenzione aggiungere il core FCEUMM.
